CREATE USER KIM IDENTIFIED BY 1234;
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
SELECT USERNAME, ACCOUNT_STATUS, DEFAULT_TABLESPACE, CREATED FROM DBA_USERS WHERE USERNAME = 'KIM';
ALTER USER KIM IDENTIFIED BY 5678;
ALTER USER KIM ACCOUNT LOCK;
ALTER USER KIM ACCOUNT UNLOCK;
ALTER USER KIM DEFAULT TABLESPACE USERS;
ALTER USER KIM QUOTA UNLIMITED ON USERS;
SELECT TABLESPACE_NAME, USERNAME, MAX_BYTES FROM DBA_TS_QUOTAS;
ALTER USER KIM QUOTA 20M ON USERS;
DROP USER KIM;
SELECT USERNAME, ACCOUNT_STATUS, DEFAULT_TABLESPACE, CREATED FROM DBA_USERS WHERE USERNAME = 'KIM';
----------------------------------------------------------
CREATE USER KIM IDENTIFIED BY 1234;
GRANT CREATE SESSION TO KIM;
GRANT CREATE TABLE TO KIM;
GRANT SELECT ON DEPT TO KIM;
REVOKE CREATE SESSION FROM KIM;
----------------------------------------------------------
GRANT CONNECT, RESOURCE TO LEE IDENTIFIED BY 5678;
REVOKE CONNECT, RESOURCE FROM LEE;
